### ISSUE TITLE
No module torch found.

### ISSUE THREAD

**Issue by jidroid404** [unit8co/vegans#1]
While running the jupyter notebooks as such , I am getting 
ModuleNotFoundError: No module named 'torch'
even though I've stable Pytorch1.0 installed in conda env where I am running the notebooks.
What could be the reasons?

**Comment by ramana1dev** [comment]
Install torch using pip

**Comment by TheMP** [comment]
@jidroid404 Make sure torch is available in your jupyter notebook environment, ie. jupyter is using your conda env. In the edge case try installing torch by typing `!pip install torch` in your notebook.
