### ISSUE TITLE
General WGAN-GP Question

### ISSUE THREAD

**Issue by jlevy44** [unit8co/vegans#10]
Hey there, amazing scripts here!

I have a general inquiry about WGAN training. I've implemented your package and started training the model. For some reason, I am getting a loss curve as such:

![training_curve](https://user-images.githubusercontent.com/19698023/59608238-844f3600-9147-11e9-8e06-8c02a12d4b9b.png)

The discriminator loss keeps increasing. I am only using MLPs as the generator and discriminators with a symmetric topology. I know this isn't a help forum, but through my readings, I've found people prefer WGAN because of stability in training. What would you recommend to do, or is this a bug (maybe sign of loss function is flipped)?

**Comment by jlevy44** [comment]
Thanks!

**Comment by jlevy44** [comment]
Some more details:

The number of latent variables that I'm sampling from is 100, and upscaling to 300k features.

**Comment by JurijsNazarovs** [comment]
@jlevy44 did you figure out what was the issue and if this was an issue?

**Comment by joonas-yoon** [comment]
+1. I am wondering that, too
