### ISSUE TITLE
WGAN init 

### ISSUE THREAD

**Issue by San-Holo** [unit8co/vegans#9]
Hello,

I'm using your awesome library for a project, as a baseline before evaluating my own models. But when I want to initialize a wasserstein GAN using the class you wrote, it's giving me a TypeError, usually observed when an object is not properly inherited or when too many arguments are given to its constructor.

Your WGAN class inherits from the GAN one, so there's no need to specify a super().__init__() in a specific __init__ in WGAN. However, it's not working and I might do something really bad without realizing it. I'm asking myself if everything's not coming from the version I'm using since it's definitely a matter of constructors, or if I should modify it directly.

Here is the call to your constructor: (I put an alias on the import, in lower case)

![image](https://user-images.githubusercontent.com/23722160/59356089-730dc000-8d28-11e9-9fb5-95a5b0475184.png)

And here is the error:

![image](https://user-images.githubusercontent.com/23722160/59356200-ae0ff380-8d28-11e9-8be0-fc705172c594.png)

Thank you in advance !

**Comment by San-Holo** [comment]
Actually, I just decided to initialize it just with a generator, a discriminator and a dataloader, step by step adding more arguments and it's working fine, except when it comes to the "device" one. It's the only one which creates something weird.

**Comment by hrzn** [comment]
Hi San-Holo,
Could you provide the full stack trace, as well as the version of all the libraries you are using? Also, did you install vegans using pip or are did you clone latest version of the code on github?

**Comment by San-Holo** [comment]
I found the problem. In the code provided via a pip install, your GAN class doesn't have a device argument. So it's a matter of version as I thought :)

![image](https://user-images.githubusercontent.com/23722160/59358097-422f8a00-8d2c-11e9-99a2-a3c9e85e5955.png)

**Comment by San-Holo** [comment]
So, as expected, it certainly comes from the pip version. I don't know if it's a huge thing, since the device in the pip version is initialized via:

`torch.device("cuda:0" if torch.cuda.is_available() else "cpu")`

which is good.

I hope that nothing else is different. If so, the pip version is not safe, and an update either of the pip repo or of the doc is necessary :)

Thank you for your help !

**Comment by tneuer** [comment]
We will close this issue as the library was completely restructured. We hope you think about using it again and reporting issues as now we are back on active development :)
